# Generated by Django 4.2.7 on 2023-11-14 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_root', models.CharField(max_length=100)),
                ('categ1', models.CharField(blank=True, max_length=100, null=True)),
                ('categ2', models.CharField(blank=True, max_length=100, null=True)),
                ('categ3', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('properties', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMMparser.pages')),
            ],
        ),
    ]
