# Generated by Django 4.2.7 on 2023-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMparser', '0003_pages_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='imageio',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
